[package]
name = "kazm"
version = "0.1.0"
authors = ["pete"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libkazm = { path = "libkazm" }
log = "0.4.14"
simple_logger = "1.11.0"
ctrlc = "3.1.9"