[package]
name = "libkazm"
version = "0.1.0"
authors = ["pete"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.20"
strum_macros = "0.20"
log = "0.4.14"
ctrlc = "3.1.9"
